import Head from "next/head";
import Carousel from "~/components/carousel/Carousel";
import { slides } from "../utils/slides/slides"
import Slide from '~/components/carousel/Slide'
export default function Home() {
  const formattedSlides = slides.map((slide) => {
    return <Slide slide={slide} key={slide.title} />;
  })
  return (
    <>
      <Head>
        <title>Church of Christ</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center">
        <h1 className='text-red-800 italic'>
          Come to Me, all you who labor and are heavy laden, 
          and I will give you rest. Take My yoke upon you and learn from Me, 
          for I am gentle and lowly in heart, and you will find rest for your souls.
          For My yoke is easy and My burden light. <span>(Matthew 11:28-30)</span>
        </h1>
        <h1 className='italic text-xl'>Worshiping God in Spirit & Truth (John 4:24)</h1>
        <div className='flex'>
          <Carousel>
            {formattedSlides}
          </Carousel>
        </div>
      </main>
    </>
  );
}

